apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpweb
  template:
    metadata:
      labels:
        app: httpweb
    spec:
      containers:
        - name: httpweb
          image: httpweb:latest
          ports:
            - containerPort: 80
